# Database Configuration
db.url=jdbc:sqlite:mail.db

# For MySQL (???????????????? ??? ????????????? MySQL)
# db.url=jdbc:mysql://localhost:3306/maildb?useSSL=false&serverTimezone=UTC
# db.user=root
# db.password=password